### ISSUE TITLE
Move BrowserModule from TreetableModule.

### ISSUE THREAD

**Issue by parth42** [mlrv/ng-material-treetable#17]
BrowserModule already been imported in AppModule so do not need to include it again in TreetableModule. Otherwise users will have an error says, "Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead."

**Comment by mlrv** [comment]
Thanks for reporting this, will definitely fix it as soon as I have some free time

**Comment by spbalu95** [comment]
I am also getting same issue when try to integrate ng-material-treetable  in angular application.

> core.js:15723 ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by mlrv** [comment]
Should be fixed with [0.4.1](https://github.com/mlrv/ng-material-treetable/releases/tag/0.4.1)

**Comment by TnCoders** [comment]
Are you sure it's Fixed cause i'm using     "ng-material-treetable": "^0.5.3",
 and i got the exact same error:

`core.js:9110 ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

**Comment by bard0x** [comment]
> Are you sure it's Fixed cause i'm using "ng-material-treetable": "^0.5.3",
> and i got the exact same error:
> 
> `core.js:9110 ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

Same issue for me with the 0.5.3.

**Comment by TnCoders** [comment]
Should re-open This Closed issues

**Comment by mlrv** [comment]
Will investigate, thanks for reporting 👍

**Comment by TnCoders** [comment]
> Will investigate, thanks for reporting 👍

Please if you have any temporary solution  to fix this please tell me how because i must deliver something today with your Treetable and im Stuck

**Comment by TnCoders** [comment]
Hello, Is there any news about this bug please ?

**Comment by coolrb** [comment]
Any update on this Bug? Or workaround

**Comment by TnCoders** [comment]
Still nothing
