### ISSUE TITLE
 Unnecessary console.logs in formatElevation function

### ISSUE THREAD

**Issue by Stromwerk** [mlrv/ng-material-treetable#26]
I've started using this plugin and it is perfect for my needs, however I've noticed excessive logging in the console, coming from what seems to be the `formatEleveation` function which has a `console.log(this.options);` call, which produces the excessive logging.

**Comment by mlrv** [comment]
Hi @Stromwerk, thanks for pointing this out. That `console.log` should definitely not belong there.

**Comment by mlrv** [comment]
What version of the library are you using?

**Comment by Stromwerk** [comment]
I'm using version `0.5.1`

**Comment by mlrv** [comment]
Fixed in `0.5.2`
