### ISSUE TITLE
Add angular material dependencies

### ISSUE THREAD

**Issue by Stromwerk** [mlrv/ng-material-treetable#27]
When installing the library on a fresh project generated by the angular-cli it errors out with `Cannot find module '@angular/material'`

Steps to reproduce:
1. `ng new project-name`
2. `npm install ng-material-treetable`
3. Add `TreeTableModule` to `AppModule`
4. `ng serve` and the project doesn't build because of the error

I know this library is material based (it even has it in the name), however I still think it would be good to add the dependencies, or at least add it to the installation guide, because there is the potential for confusion.

To be specific - all the angular material modules are needed - `@angular/material` `@angular/cdk` `@angular/animations`

**Comment by mlrv** [comment]
Hi @Stromwerk, you're right it would probably be a good idea to add it to  the `peerDependencies` of the library and mention it in the installation instructions.

I'll do it asap.
