### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CWBittencourt** [mlrv/ng-material-treetable#34]
Can you help me with this error?
![image](https://user-images.githubusercontent.com/19273774/65831929-e6661e00-e294-11e9-9aed-a59e56500065.png)

**Comment by mlrv** [comment]
You spelled `treee` instead of `tree` 😉

**Comment by CWBittencourt** [comment]
sorry
![image](https://user-images.githubusercontent.com/19273774/65832276-e3206180-e297-11e9-8f2d-33edff722c06.png)
![image](https://user-images.githubusercontent.com/19273774/65832282-f7645e80-e297-11e9-90cf-0e4dd790b7ef.png)

**Comment by mlrv** [comment]
Have you imported the package in your main module?
```
import { TreetableModule } from 'ng-material-treetable';

@NgModule({
    ...
  imports: [
    ...
    TreetableModule // <--- this
  ],
  ...
})
export class AppModule { }
```

**Comment by CWBittencourt** [comment]
yes
![image](https://user-images.githubusercontent.com/19273774/65832669-41037800-e29d-11e9-98b1-3088bacca99f.png)

**Comment by mlrv** [comment]
And I suppose GridModule is correctly imported in AppModule?

Can you reproduce this on stackblitz so I can have a proper look at it?

**Comment by CWBittencourt** [comment]
Thank you. Working
![image](https://user-images.githubusercontent.com/19273774/65832702-c5ee9180-e29d-11e9-9895-8da668e2fcea.png)
