### ISSUE TITLE
Add code

### ISSUE THREAD

**Issue by CWBittencourt** [mlrv/ng-material-treetable#35]
Could you add this code to the project to facilitate the retrieval of information for deletion and editing?

in treetable.component.ts

@Output() lineClick: Subject<T> = new Subject();
  onLineClick(line: T): T{
      return line;
  }

in treetable.component.html add (click)="onLineClick(element)"

 mat-cell *matCellDef="let element" [ngClass]="{'vertical-separator': options.verticalSeparator}" (click)="onLineClick(element)"
    

result on click

![image](https://user-images.githubusercontent.com/19273774/65836289-9ef88580-e2c6-11e9-9bf5-baf3a63cf47e.png)

**Comment by mlrv** [comment]
Hi @CWBittencourt , there's already a `nodeClicked` event for this use case, see [here](https://github.com/mlrv/ng-material-treetable#events)

**Comment by CWBittencourt** [comment]
This event only works for the main node. What I proposed works for any selected row. I need to retrieve the value of any selected row and not just the main node.

**Comment by peterAzv** [comment]
I don't know this issue was closed a event to get the values from the line is very usefull.
