### ISSUE TITLE
Filter TreeTable by predicate

### ISSUE THREAD

**Issue by coder-cmd** [mlrv/ng-material-treetable#41]
Hello @all,

i need urgently your help.. is there are any way to filter the data in the treetable like in the mat-table? 

Best thanks and regards!

**Comment by coder-cmd** [comment]
Can anyone help me, please?

**Comment by coder-cmd** [comment]
??

**Comment by mlrv** [comment]
Hi @coder-cmd, can you please elaborate a bit more on what exactly you're trying to achieve?

**Comment by coder-cmd** [comment]
Hi @mlrv first of all thanks a lot for ur response🙏🏼 I have elements like a datepicker and an input field. So my data model has properties like validfrom, validto, id and a name. I want now to set a date range on my datepicker and enter a search key in the input field and this should be filter my dataset on the Tree table. But i dont have any idea, how this will be done. So i hope you can support me.

**Comment by mlrv** [comment]
OK that makes sense, can you provide a minimal, reproducible example of what you have right now? There's definitely ways to achieve what you want, but it'd be good to see where you're starting from.

**Comment by coder-cmd** [comment]
Hey @mlrv i have build a example how it looks on https://stackblitz.com/edit/angular-qnlruj, base on ur example. My Problem is now in the method applyFilters ..
