### ISSUE TITLE
Conflicting selector

### ISSUE THREAD

**Issue by gund** [mlrv/ng-material-treetable#5]
Hi, great library!

You named your component as `ng-treetable` but I think it's a bad practice to use `ng-` prefix for custom components as they might clash with Angular components in the future.

Instead you should pick unique prefix for this library (maybe `nmt-` that stands for **N**g-**M**aterial-**T**reetable?).

**Comment by mlrv** [comment]
Hey @gund, thanks for the feedback, that is actually a very good point, and I do like the idea of using `nmt` as a prefix.

However, that is a breaking change so ideally I'd like to implement that with the next major release. I do have a few things in mind that I want to implement before releasing `1.0.0`, so this will probably go with that as well :)
